### ISSUE TITLE
Using tag from a displax screen make listener thread crash

### ISSUE THREAD

**Issue by tito** [kivy/oscpy#73]
**Describe the bug**
When using a DISPLAX tag supporting TUIO on a DISPLAX screen, oscpy TUIO listener crash:

```
❯ oscli dump -P 3333
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/tito/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/tito/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/server.py", line 338, in _run_listener
    self._listen()
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/server.py", line 386, in _listen
    for address, tags, values, offset in read_packet(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 416, in read_packet
    timetag, messages = read_bundle(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 390, in read_bundle
    address, tags, values, off = read_message(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 309, in read_message
    value, off = parse(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 202, in parse
    raise ValueError(
ValueError: no known parser for type hint: 116, value: b'#bundle\x00\x00\x00\x01\x86\xa5l+D\x00\x00\x008/tuio2/frm\x00\x00,itis\x00\x00\x00\x00\x08\xdf\xc2d\x01\xf1`\xd6\x04\x18\x92 \x08\x12*Ultra 023009000107\x00\x00\x00\x00\x00\x10/tuio2/alv\x00\x00,\x00\x00\x00'
```

**To Reproduce**
Code example showing the issue:

```
❯ oscli dump -P 3333
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/tito/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/tito/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/server.py", line 338, in _run_listener
    self._listen()
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/server.py", line 386, in _listen
    for address, tags, values, offset in read_packet(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 416, in read_packet
    timetag, messages = read_bundle(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 390, in read_bundle
    address, tags, values, off = read_message(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 309, in read_message
    value, off = parse(
  File "/home/tito/code/oman/.venv/lib/python3.9/site-packages/oscpy/parser.py", line 202, in parse
    raise ValueError(
ValueError: no known parser for type hint: 116, value: b'#bundle\x00\x00\x00\x01\x86\xa5l+D\x00\x00\x008/tuio2/frm\x00\x00,itis\x00\x00\x00\x00\x08\xdf\xc2d\x01\xf1`\xd6\x04\x18\x92 \x08\x12*Ultra 023009000107\x00\x00\x00\x00\x00\x10/tuio2/alv\x00\x00,\x00\x00\x00'
```

**Expected behavior**
I should not expect crashing. Maybe due to type or bundle issue, will search.

**Logs/output**

**Platform (please complete the following information):**
 - OS: Windows 10, Arch linux.
 - Python 3.9 + 3.11
 - oscpy 0.6.0

**Comment by tito** [comment]
So actually, this is part of TUIO 2.0 Specifications, which are not supported by oscpy

**Comment by tito** [comment]
https://github.com/kivy/oscpy/compare/master...tito:oscpy:displax-tag

**Comment by tshirtman** [comment]
> [master...tito:oscpy:displax-tag](https://github.com/kivy/oscpy/compare/master...tito:oscpy:displax-tag)

Nice, feel free to do an MR for it, it was indeed in the TODO i never got back to.
